### ISSUE TITLE
Be able to use ValueObject inside messages (e.g. commands and events)

### ISSUE THREAD

**Issue by CipherdevNL** [ecotoneframework/ecotone#13]
**Description**  
When building a domain I often use ValueObjects for the aggregate identifiers.
This helps to encapsulate logic needed to generate those id's. 

With Ecotone framework it's possible to automatically route messages to the aggregate itself without manual loading the aggregate.
But currently Ecotone is unable to interpet a ValueObject as `TargetAggregateIdentifier`, this will result in a `Value must have a scalar type for the operator EQUALS.` inside the `EventSourcingRepository`.
This can be resolved by mapping the value object to a scalar type inside the repository.
After some digging through the code and multiple (hackey) attempt I was unable to find a way to do this.

This made my conclusion that's currently not possible to perform this conversion, or I overlooked some solution.

So the feature request is to add a mechanisme to make it possible to convert identifiers inside the `EventSourcingRepository` of ecotone/event-sourcing.

The reason I'm not switching to scalar types inside the message, is because I prefer to be consistent with value objects inside the domain code. Otherwise the domain will be bloated with mapping back and forward of value objects.

**Example**  
Before:

```PHP
<?php

final class ImportCourse
{
    public function __construct(
        #[TargetAggregateIdentifier]
        public readonly string $id,
        public readonly Education $education,
        public readonly Acknowledgement $acknowledgement,
        public readonly string $name,
        public readonly string $sector
    ) {
    }
}

```

After:
```PHP
<?php

final class ImportCourse
{
    public function __construct(
        #[TargetAggregateIdentifier]
        public readonly CourseId $id,
        public readonly Education $education,
        public readonly Acknowledgement $acknowledgement,
        public readonly string $name,
        public readonly string $sector
    ) {
    }
}

```

**Comment by dgafka** [comment]
That's a great proposal. :) 
Starting from with `1.15.0` it's now possible to use `Value Objects` inside Command/Event/Queries for Aggregates. 

 Thank you for trying on your own ;)

**Comment by CipherdevNL** [comment]
Thanks for the quick work :), have implemented it and works like a charm!

Thank you very much :)
