### ISSUE TITLE
Snapshot mechanisme for large aggregates

### ISSUE THREAD

**Issue by CipherdevNL** [ecotoneframework/ecotone#15]
**Description**  
Sometimes it's possible to have large aggregate instances that generate a lot of events. (e.g. a scrape session)
When an aggregate has a lot of events it will result in a high rebuild time of the aggregate.
This results in slow speeds inside the write models.

A solution to this problem is to take snapshots of the state and save them inside a memcache or database.
Currently (as far I know of) ecotone doesn't have support for generating a snapshot of an event sourced aggregate, making it difficult to have large aggregates.

Another option is to split the aggregate into smaller aggregates, but in my use-case this is not possible (with my knowledge).
The scraper is responsible to scrape multiple vacancies from an external site, which will result in 200.000+ events.
And all those events are required in a single aggregate, because the aggregate must be able to determine if vacancies are vanished.

**Example**  
I've no real example on how this will look like inside Ecotone.
But as reference the (deprecated) [prooph implementation](http://docs.getprooph.org/event-sourcing/snapshots/snapshot_store/snapshot_store.html#4-3-3-1) might be interesting?
What I really like from their implementation is the ability to chain / combine multiple snapshot stores so you have a "hot and cold" snapshot store.

**Comment by dgafka** [comment]
I've idea how to approach that. This will be included in event-sourcing package.   
I will start implementing it next week :)

**Comment by CipherdevNL** [comment]
Cool! If I can help somehow feel free to ask!

**Comment by dgafka** [comment]
Hey @CipherdevNL `snapshots are available` from `1.21.0` version of Ecotone.
You can enable them using `Service Context`: https://docs.ecotone.tech/modelling/event-sourcing/snapshoting

Besides that newest version of Ecotone comes with `Document Store` as storage for snapshots and way to store projections: https://docs.ecotone.tech/modelling/event-sourcing/setting-up-projections#document-store

Have fun :)
