### ISSUE TITLE
Eventsourcing / with activated Snapshots throw on Aggregate access

### ISSUE THREAD

**Issue by aheissenberger** [ecotoneframework/ecotone#16]
**Ecotone version(s) affected**: ecotone/pdo-event-sourcing 1.22.5

**Description**  
When Snapshots are activated, Aggregates fail to load the snapshot from document store and throws an exception if threshold has not been reached and as a result no snapshot exists.

**How to reproduce**  
```php
#[ServiceContext]
    public function dbEventStorage()
    {
        $snapshotGivenAggregates = [Wallet::class];
        $threshold = 100;
        return [
            DbalConfiguration::createWithDefaults()
            ->withTransactionOnCommandBus(false)
            ->withDocumentStore(initializeDatabaseTable: true),
            // setting updb event sourcing
            EventSourcingConfiguration::createWithDefaults()
                 ->withSnapshots($snapshotGivenAggregates, $threshold)
           
        ];
    }
```
any update to the aggregate will throw an exception here `$this->documentStore->getDocument` which is not catched:
https://github.com/ecotoneframework/event-sourcing/blob/15d01c74272d6ae27cb4df71c1eb25908a577b2f/src/EventSourcing/EventSourcingRepository.php#L66-L72

**Possible Solution**  
* catch the exception and load all events

PR: https://github.com/ecotoneframework/event-sourcing/pull/4

**Context**

**Comment by dgafka** [comment]
Fix released in Ecotone 1.22.10 version.

Thank you for the fix @aheissenberger :)
