### ISSUE TITLE
There is problem with configuration. Interface to call Ecotone\EventSourcing\Config\ProjectionFlowController:preSend was never registered via related interfaces.

### ISSUE THREAD

**Issue by aidan-casey** [ecotoneframework/ecotone#19]
**Ecotone version(s) affected**: 1.30.1

**Description**  
I am having some trouble when I try to run any projection commands in the context of Laravel. In digging into the issue, it seems to stem from line 181 of `ServiceActivatorBuilder`. Doing a dump of the `$interfacesToCall` property on the `InterfaceToCallRegistry` reveals that this class `ProjectionFlowController` is not present, but it is present earlier on in the `EventSourcingModule` config class.

**Comment by aidan-casey** [comment]
So I have tracked this down to the fact that the `InterfaceToCallRegistry` is locked by the time it is called in the `ServiceActivatorBuilder` and `ProjectionFlowController` is not appropriately cached in that registry by that time. I can prove this out by unlocking the registry in the `getFor` method.

I'm not entirely sure the purpose of this lock, so not sure the best approach to resolving the problem.

**Comment by dgafka** [comment]
Ecotone optimizes and caches all the configuration on the first run. On the next run it's just make use of the existing cached configuration. 

However that bug should affect Symfony and Lite version too, so that's a bit odd. 
Can publish demo project with this bug on github, so I can check it out?

**Comment by aidan-casey** [comment]
@dgafka - That makes sense, it just seems like the `ProjectionFlowController` is just never cached. See [here](https://github.com/aidan-casey/ecotone-bug-19) for a demo project with the bug.

**Comment by aidan-casey** [comment]
@dgafka - This should be reopened as the issue still persists.

**Comment by dgafka** [comment]
Reopen to recheck

**Comment by dgafka** [comment]
@aidan-casey I've run the projection in pollable way, it worked. 
This is the repo which runs the projection: https://github.com/dgafka/laravel-ecotone-bug-19

Can you provide PR or push changes to your repo that make the projection fail?

**Comment by aidan-casey** [comment]
@dgafka - I am unable to reproduce this issue on v1.32.0. I will go ahead and close this issue since it does seem to be resolved.
