### ISSUE TITLE
Class "Doctrine\Common\Cache\FilesystemCache" not found

### ISSUE THREAD

**Issue by aidan-casey** [ecotoneframework/ecotone#20]
**Ecotone version(s) affected**: 1.31.1

**Description**  
The latest patch actually causes another problem. The package `doctrine/cache` is being abandoned and in it's current state it no longer includes the `FilesystemCache` class which is required by the JMS `SerializerBuilder` class.

**How to reproduce**  
Attempt to run a projection.

**Possible Solution**  
Possibly upgrade JMS serializer or move to another package.

**Comment by aidan-casey** [comment]
JMS Serializer v3.13 begins to suggest `symfony/cache` instead.

**Comment by dgafka** [comment]
By this problem still persist (https://github.com/ecotoneframework/ecotone/issues/19) you mean there still is a problem and the problem now is about `FilesystemCache`?

**Comment by dgafka** [comment]
In that case I will take look once more on #19.   
Thank you for the contribution, your PR https://github.com/ecotoneframework/jms-converter/pull/2 is now merged, so I close the issue  :)
