### ISSUE TITLE
General Package Thoughts

### ISSUE THREAD

**Issue by aidan-casey** [ecotoneframework/ecotone#22]
I am still working on wrapping my head around this package, but in my brief time poking around, I had a few thoughts I wanted to share in hopes that they are helpful. I did not have a great place to put this, so hopefully, this issue suffices.

The first thought is that this project may benefit from a monorepo tool such as symplify/monorepo-builder. I suggest this because it seems to me that parts of the central ecotone repository (e.g., Lite) are unnecessary to include for the Laravel package. On the other hand, many of the other packages (e.g., Event-Sourcing) could benefit from being stored alongside the framework for the benefit of developer visibility.

The second thought I would like to present is better documentation around providing adapters. Having documented the essential interfaces to implement would make it easy for people to contribute that way, allowing for new adapters (e.g., Laravel Eloquent, Eventstore DB, etc.) to be created.

Finally, I would like to suggest that, while I appreciate the immense work you have put into this package, parts of it are a little over-engineered. I only want to bring this to your attention because I think re-envisioning some of the structure would make it much easier for other developers to come into the system and get an idea of what is happening. I know event sourcing can be complex; I'm just suggesting figuring out a way to simplify the approach to avoid a maintenance burden where you, or a select few, are the only contributing.

I look forward to assisting as I can around here and am thankful for the work you have already put in!

**Comment by dgafka** [comment]
As I had feeling you've tackled 2 topics in here:
- Introducing Mono-repo
- Sharing maintenance of the project. Bringing more contributors to Ecotone
	*  Better documentation on how to write adapters by the community
	*  Lowering codebase entrypoint for new contributors
	
I've created 2 github's discussions accordingly:
[Introducing Monorepo](https://github.com/ecotoneframework/ecotone/discussions/23)
[Sharing maintenance of Ecotone](https://github.com/ecotoneframework/ecotone/discussions/24)

Let me know, if you're okey with moving the discussion there and closing this issue? :)

**Comment by aidan-casey** [comment]
I think you're right! I look forward to continuing the conversations there. 🙂
