### ISSUE TITLE
Orchestra Testbench Problems with Laravel Package

### ISSUE THREAD

**Issue by aidan-casey** [ecotoneframework/ecotone#25]
**Ecotone version(s) affected**: 1.32.0

**Description**

The test package for Laravel `orchestra/testbench` keeps an instance of the Laravel framework in it's source code for running tests against. When attempting to run tests concerning the Ecotone service provider, they fail due to  `Ecotone\AnnotationFinder\FileSystem\FileSystemAnnotationFinder` trying to load the composer files from the Laravel framework app instance, not the root `composer.json` file in the package.

**Comment by dgafka** [comment]
This will be fixed in Ecotone 2.0.0 :) 

Feel free to reopen in case of need.
