### ISSUE TITLE
Ecotone\Laravel\CombinedLogger incompatible with Psr\Log\LoggerInterface and Psr\Log\AbstractLogger on PHP 8.1

### ISSUE THREAD

**Issue by Rhaal** [ecotoneframework/ecotone#27]
**Ecotone version(s) affected**: 1.32 (possibly earlier ones too)

**Description**  
Despite being an implementation of the `Psr\Log\LoggerInterface` , the `Ecotone\Laravel\CombinedLogger` class is not compatible with said interface
![image](https://user-images.githubusercontent.com/35896/177721641-498c8c64-83ae-4864-a6ea-8f8ebbfcae51.png)

**How to reproduce**  

1. Setup a new project, e.g. based on Laravel, by launching ` curl -s "https://laravel.build/log-issue-app?devcontainer" | bash`
2. Add the official ecotone package via `composer require ecotone/laravel`
  a. To use the Composer executable within the Laravel Sail container, launch `sail composer require ecotone/laravel`

**Possible Solution**  
Change the `CombinedLogger::log` method signature from
```php
public function log($level, $message, array $context = array())
```
to
```php
public function log($level, string|\Stringable $message, array $context = []) : void
```
![image](https://user-images.githubusercontent.com/35896/177723861-211ba256-98c9-4519-a054-fe146b9ea961.png)
**Context**  
Found during an exploratory setup following [Installation - Ecotone](https://docs.ecotone.tech/install-php-service-bus)

**Caveats**
Due to the presence of the `\Stringable` interface, this would make the package incompatible with PHP < 8.0

**Open PRs**
https://github.com/ecotoneframework/laravel/pull/3

**Comment by dgafka** [comment]
Fix released with Ecotone `1.32.2`, thanks to @aidan-casey  :)

**Comment by dgafka** [comment]
I am impressed by the description. 
Having such detailed issue is just pure gold :1st_place_medal:

**Comment by Rhaal** [comment]
🙏Thanks, and most of all thanks for taking care of this in such a timely fashion!
