### ISSUE TITLE
Rename Laravel / Symfony Packages?

### ISSUE THREAD

**Issue by aidan-casey** [ecotoneframework/ecotone#33]
I am wondering if we should rename the Laravel / Symfony packages simply to get them into their own namespace. Something along the lines of `Ecotone\Infrastructure\Laravel` maybe?

**Comment by dgafka** [comment]
I am closing this for now, as I've moved development repository to [ecotoneframework/ecotone-dev](https://github.com/ecotoneframework/ecotone-dev). 

Feel free to reopen it there :)
