### ISSUE TITLE
WrongHandlerAmountException

### ISSUE THREAD

**Issue by Tuzex** [ecotoneframework/ecotone#4]
**Ecotone version(s) affected**: 1.3.7

**Description**  
I have two `state-stored aggregate` as two sagas. Both listen to one particular event. I have only one general repository implements `StandardRepository` interface.

Exception message: `Service Activator - Ecotone\Modelling\SaveAggregateService::save can't be registered as second handler for unicasting dispatcher. The first is Service Activator - Ecotone\Modelling\SaveAggregateService::save`.

A specific event can have two event handlers in the `channelResolver`, but  `Eventsave` not (DirectChannel).

**How to reproduce**  
Create two sagas with a method, that listens to one particular domain event.

**Comment by dgafka** [comment]
@Tuzex thank you for reporting the issue. 

This is now fixed with latest version of Ecotone. :)
