### ISSUE TITLE
Unable to run asynchronous commands

### ISSUE THREAD

**Issue by unixslayer** [ecotoneframework/ecotone#45]
**Ecotone version(s) affected**: 1.32.2

**Description** 

Like in the title, I'm unable to run async commands. With following configuration:

```php
<?php

use Ecotone\Dbal\Configuration\DbalConfiguration;
use Ecotone\Dbal\DbalBackedMessageChannelBuilder;
use Ecotone\Messaging\Attribute\ServiceContext;

final class EcotoneConfiguration
{
    #[ServiceContext]
    public function getDbalConfiguration(): DbalConfiguration
    {
        return DbalConfiguration::createWithDefaults()
            ->withTransactionOnCommandBus(isTransactionEnabled: false)
        ;
    }

    #[ServiceContext]
    public function supplierSyncChannel(): DbalBackedMessageChannelBuilder
    {
        return DbalBackedMessageChannelBuilder::create(channelName: "supplier_sync");
    }
}
```

```php
<?php

use Ecotone\Messaging\Attribute\Asynchronous;
use Ecotone\Modelling\Attribute\CommandHandler;

final class Supplier
{
    #[Asynchronous('supplier_sync')]
    #[CommandHandler(endpointId: 'supplier_create_endpoint')]
    public static function create(CreateSupplierCommand $command): array
    {
        // ...
    }
```

Commands are executed immediately after send. It does not matter if command is send with routing key or without.

**Comment by dgafka** [comment]
Hey @unixslayer,

Can you provide running example just like in [quickstart-examples](https://github.com/ecotoneframework/quickstart-examples)?

**Comment by unixslayer** [comment]
@dgafka the problem is that after creating this issue I tried to replicate it by modifying quickstart-example code to send asynchronous command and it worked.

**Comment by dgafka** [comment]
So it works now? Maybe cache was stale? :)

**Comment by unixslayer** [comment]
What I've meant is that I've changed quickstart-example to duplicate the issue there, but it worked. Unfortunately, it still does not work in the project. I'm using just the configuration I paste here and cache was removed completely before testing. Am I missing something? Not all commands are handled by asynchronous channels.

**Comment by dgafka** [comment]
That's all what is needed.

My guess would be that it have not read your `ServiceContext` for some reason.
Can you verify, it actually use this code?

Hint.
If you're using symfony, then this code will execute before dumping cache, next runs will not execute it as the configuration is already cached.

**Comment by unixslayer** [comment]
Yes, `ServiceContext` was read correctly. Debugging message handling I noticed that channel is also registered.

![Zrzut ekranu z 2022-07-22 09-01-13](https://user-images.githubusercontent.com/1131246/180382671-95b03176-fa3c-4246-9a49-d21f7636e147.png)

**Comment by dgafka** [comment]
Hmm, I would need to reproduce the error to check it. 
If you could cut problematic part of your code and share (can be privately) that would be useful  :)

**Comment by dgafka** [comment]
I've moved development repository to [ecotoneframework/ecotone-dev](https://github.com/ecotoneframework/ecotone-dev).

Feel free to reopen issue there :)
