### ISSUE TITLE
Database Good Poller scheduling

### ISSUE THREAD

**Issue by ubsysdev** [ecotoneframework/ecotone#46]
Good day

I will like to know how can I schedule a task with a database value.

`#[Poller(databaseValue)]`

Thank you

**Comment by dgafka** [comment]
Hello @ubsysdev,

Currently Ecotone does not support that. 
I think this would be good addition, to actually support that. 

In that case I am leaving this ticket open. 
Feel free to introduce PR for this. In case of questions I am here to help :)

**Comment by dgafka** [comment]
I've moved development repository to [ecotoneframework/ecotone-dev](https://github.com/ecotoneframework/ecotone-dev).

Feel free to reopen issue there :)
