### ISSUE TITLE
ecotone.tech is not loading

### ISSUE THREAD

**Issue by mailopl** [ecotoneframework/ecotone#5]
**Ecotone version(s) affected**: all

**Description**  

**How to reproduce**  
Load http://ecotone.tech/

**Possible Solution**  
Reconfigure DNS 

**Context**  
Website is not loading, docs are not loading etc.

**Comment by dgafka** [comment]
@mailopl the website is back.
Soon there will be blog set up for ecotone.tech and due to those changes, website went down for some time. 

It's going to be up and running now. :)

**Comment by mailopl** [comment]
thank you!
